import { initMcpTada, readOnly } from "mcp-tada";
import type { ReadOnlyToolNames } from "mcp-tada";
import { describe, expectTypeOf, test } from "vitest";
import { defineTool, defineTools } from "../src/define.js";
import type { IntrospectionOf } from "../src/define.js";

const echoInput = {
  type: "object",
  properties: { message: { type: "string" } },
  required: ["message"],
} as const;

const sumInput = {
  type: "object",
  properties: { a: { type: "number" }, b: { type: "number" } },
  required: ["a", "b"],
} as const;

const sumOutput = {
  type: "object",
  properties: { total: { type: "number" } },
  required: ["total"],
} as const;

const echo = defineTool({
  name: "echo",
  description: "Echoes a message back",
  inputSchema: echoInput,
  handler: async (args) => {
    expectTypeOf(args).toEqualTypeOf<{ readonly message: string }>();
    return { content: [{ type: "text" as const, text: args.message }] };
  },
});

const sum = defineTool({
  name: "sum",
  inputSchema: sumInput,
  outputSchema: sumOutput,
  handler: async (args) => {
    expectTypeOf(args).toEqualTypeOf<{ readonly a: number; readonly b: number }>();
    // The bare structured content is a valid return...
    return { total: args.a + args.b };
  },
});

const sumWrapped = defineTool({
  name: "sum-wrapped",
  inputSchema: sumInput,
  outputSchema: sumOutput,
  handler: async (args) => {
    // ...and so is the explicit wrapped shape, e.g. to customize `content`.
    const total = args.a + args.b;
    return {
      structuredContent: { total },
      content: [{ type: "text" as const, text: String(total) }],
    };
  },
});

const tools = defineTools([echo, sum, sumWrapped]);

describe("defineTool / defineTools types", () => {
  test("handler args and return are inferred from the schemas", () => {
    expectTypeOf(tools.echo.name).toEqualTypeOf<"echo">();
    expectTypeOf(tools.sum.name).toEqualTypeOf<"sum">();
  });

  test("IntrospectionOf matches the expected literal shape, mutable like a generated introspection.d.ts", () => {
    // `defineTool`'s `const` type parameters make the inferred schemas deeply readonly, but a
    // schema generated by `mcp-tada introspect` is a plain (mutable) JSON type literal.
    // `IntrospectionOf` applies `DeepMutable` so both paths produce this identical, mutable shape.
    type Expected = {
      tools: {
        echo: {
          inputSchema: {
            type: "object";
            properties: { message: { type: "string" } };
            required: ["message"];
          };
        };
        sum: {
          inputSchema: {
            type: "object";
            properties: { a: { type: "number" }; b: { type: "number" } };
            required: ["a", "b"];
          };
          outputSchema: {
            type: "object";
            properties: { total: { type: "number" } };
            required: ["total"];
          };
        };
        "sum-wrapped": {
          inputSchema: {
            type: "object";
            properties: { a: { type: "number" }; b: { type: "number" } };
            required: ["a", "b"];
          };
          outputSchema: {
            type: "object";
            properties: { total: { type: "number" } };
            required: ["total"];
          };
        };
      };
    };

    expectTypeOf<IntrospectionOf<typeof tools>>().toEqualTypeOf<Expected>();
  });

  test("plugs into initMcpTada with a correctly typed callTool, no network round trip", async () => {
    const mcp = initMcpTada<IntrospectionOf<typeof tools>>().typed(undefined as any);

    const r1 = await mcp.callTool("sum", { a: 1, b: 2 });
    if (r1.isError) throw new Error("unexpected error");
    // `IntrospectionOf` applies `DeepMutable`, so `total` is a plain mutable property here even
    // though `sumOutput` is declared `as const`, matching a schema read from a generated
    // introspection.d.ts. Output-mode typing keeps the object open to undeclared keys.
    expectTypeOf(r1.structuredContent.total).toEqualTypeOf<number>();
    expectTypeOf(r1.structuredContent["extra"]).toEqualTypeOf<unknown>();

    // No outputSchema: structuredContent is `unknown`, never `undefined`.
    const r2 = await mcp.callTool("echo", { message: "hi" });
    if (r2.isError) throw new Error("unexpected error");
    expectTypeOf(r2.structuredContent).toEqualTypeOf<unknown>();

    // @ts-expect-error unknown tool
    await mcp.callTool("nope", {});

    // @ts-expect-error missing required arg b
    await mcp.callTool("sum", { a: 1 });
  });
});

describe("IntrospectionOf carries annotations", () => {
  const annotated = defineTools([
    defineTool({
      name: "peek",
      inputSchema: { type: "object", properties: {} },
      annotations: { readOnlyHint: true, destructiveHint: false },
      handler: () => ({ content: [] }),
    }),
    defineTool({
      name: "wipe",
      inputSchema: { type: "object", properties: {} },
      annotations: { readOnlyHint: false, destructiveHint: true },
      handler: () => ({ content: [] }),
    }),
    defineTool({
      name: "plain",
      inputSchema: { type: "object", properties: {} },
      handler: () => ({ content: [] }),
    }),
  ]);
  type I = IntrospectionOf<typeof annotated>;

  test("with literal hint values, so the mcp-tada filters apply", () => {
    expectTypeOf<I["tools"]["peek"]["annotations"]>().toEqualTypeOf<{
      readOnlyHint: true;
      destructiveHint: false;
    }>();
    expectTypeOf<keyof I["tools"]["plain"]>().toEqualTypeOf<"inputSchema">();
    expectTypeOf<ReadOnlyToolNames<I>>().toEqualTypeOf<"peek">();

    const safe = readOnly(initMcpTada<I>().typed(undefined as any));
    expectTypeOf<keyof typeof safe.tools>().toEqualTypeOf<"peek">();
  });
});

describe("IntrospectionOf through defineTools", () => {
  test("a tool without outputSchema has no outputSchema key, even after AnyToolDefinition erasure", () => {
    const erased = defineTools([
      defineTool({
        name: "ping",
        inputSchema: { type: "object", properties: {} },
        handler: () => ({ content: [] }),
      }),
    ]);
    type Ping = IntrospectionOf<typeof erased>["tools"]["ping"];
    expectTypeOf<keyof Ping>().toEqualTypeOf<"inputSchema">();
  });
});
