// Generated by mcp-tada. Do not edit.
// server: memory-server@0.6.3
// protocolVersion: unknown
// capabilities.tools.listChanged: true

export type introspection = {
  "tools": {
    /**
     * Add Observations
     * Add new observations to existing entities in the knowledge graph
     */
    "add_observations": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "observations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "entityName": {
                  "type": "string",
                  "description": "The name of the entity to add the observations to"
                },
                "contents": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observation contents to add"
                }
              },
              "required": [
                "entityName",
                "contents"
              ]
            }
          }
        },
        "required": [
          "observations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "entityName": {
                  "type": "string"
                },
                "addedObservations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "entityName",
                "addedObservations"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "results"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false
      }
    },
    /**
     * Create Entities
     * Create multiple new entities in the knowledge graph
     */
    "create_entities": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "entities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the entity"
                },
                "entityType": {
                  "type": "string",
                  "description": "The type of the entity"
                },
                "observations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observation contents associated with the entity"
                }
              },
              "required": [
                "name",
                "entityType",
                "observations"
              ]
            }
          }
        },
        "required": [
          "entities"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "entities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the entity"
                },
                "entityType": {
                  "type": "string",
                  "description": "The type of the entity"
                },
                "observations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observation contents associated with the entity"
                }
              },
              "required": [
                "name",
                "entityType",
                "observations"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "entities"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false
      }
    },
    /**
     * Create Relations
     * Create multiple new relations between entities in the knowledge graph. Relations should be in active voice
     */
    "create_relations": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "relations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "description": "The name of the entity where the relation starts"
                },
                "to": {
                  "type": "string",
                  "description": "The name of the entity where the relation ends"
                },
                "relationType": {
                  "type": "string",
                  "description": "The type of the relation"
                }
              },
              "required": [
                "from",
                "to",
                "relationType"
              ]
            }
          }
        },
        "required": [
          "relations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "relations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "description": "The name of the entity where the relation starts"
                },
                "to": {
                  "type": "string",
                  "description": "The name of the entity where the relation ends"
                },
                "relationType": {
                  "type": "string",
                  "description": "The type of the relation"
                }
              },
              "required": [
                "from",
                "to",
                "relationType"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "relations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false
      }
    },
    /**
     * Delete Entities
     * Delete multiple entities and their associated relations from the knowledge graph
     */
    "delete_entities": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "entityNames": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "An array of entity names to delete"
          }
        },
        "required": [
          "entityNames"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "required": [
          "success",
          "message"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "destructiveHint": true,
        "idempotentHint": true,
        "openWorldHint": false
      }
    },
    /**
     * Delete Observations
     * Delete specific observations from entities in the knowledge graph
     */
    "delete_observations": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "deletions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "entityName": {
                  "type": "string",
                  "description": "The name of the entity containing the observations"
                },
                "observations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observations to delete"
                }
              },
              "required": [
                "entityName",
                "observations"
              ]
            }
          }
        },
        "required": [
          "deletions"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "required": [
          "success",
          "message"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "destructiveHint": true,
        "idempotentHint": true,
        "openWorldHint": false
      }
    },
    /**
     * Delete Relations
     * Delete multiple relations from the knowledge graph
     */
    "delete_relations": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "relations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "description": "The name of the entity where the relation starts"
                },
                "to": {
                  "type": "string",
                  "description": "The name of the entity where the relation ends"
                },
                "relationType": {
                  "type": "string",
                  "description": "The type of the relation"
                }
              },
              "required": [
                "from",
                "to",
                "relationType"
              ]
            },
            "description": "An array of relations to delete"
          }
        },
        "required": [
          "relations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        },
        "required": [
          "success",
          "message"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": false,
        "destructiveHint": true,
        "idempotentHint": true,
        "openWorldHint": false
      }
    },
    /**
     * Open Nodes
     * Open specific nodes in the knowledge graph by their names
     */
    "open_nodes": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "names": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "An array of entity names to retrieve"
          }
        },
        "required": [
          "names"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "entities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the entity"
                },
                "entityType": {
                  "type": "string",
                  "description": "The type of the entity"
                },
                "observations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observation contents associated with the entity"
                }
              },
              "required": [
                "name",
                "entityType",
                "observations"
              ],
              "additionalProperties": false
            }
          },
          "relations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "description": "The name of the entity where the relation starts"
                },
                "to": {
                  "type": "string",
                  "description": "The name of the entity where the relation ends"
                },
                "relationType": {
                  "type": "string",
                  "description": "The type of the relation"
                }
              },
              "required": [
                "from",
                "to",
                "relationType"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "entities",
          "relations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "destructiveHint": false,
        "idempotentHint": true,
        "openWorldHint": false
      }
    },
    /**
     * Read Graph
     * Read the entire knowledge graph
     */
    "read_graph": {
      "inputSchema": {
        "type": "object",
        "properties": {},
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "entities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the entity"
                },
                "entityType": {
                  "type": "string",
                  "description": "The type of the entity"
                },
                "observations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observation contents associated with the entity"
                }
              },
              "required": [
                "name",
                "entityType",
                "observations"
              ],
              "additionalProperties": false
            }
          },
          "relations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "description": "The name of the entity where the relation starts"
                },
                "to": {
                  "type": "string",
                  "description": "The name of the entity where the relation ends"
                },
                "relationType": {
                  "type": "string",
                  "description": "The type of the relation"
                }
              },
              "required": [
                "from",
                "to",
                "relationType"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "entities",
          "relations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "destructiveHint": false,
        "idempotentHint": true,
        "openWorldHint": false
      }
    },
    /**
     * Search Nodes
     * Search for nodes in the knowledge graph based on a query
     */
    "search_nodes": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "The search query to match against entity names, types, and observation content"
          }
        },
        "required": [
          "query"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#"
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "entities": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the entity"
                },
                "entityType": {
                  "type": "string",
                  "description": "The type of the entity"
                },
                "observations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "description": "An array of observation contents associated with the entity"
                }
              },
              "required": [
                "name",
                "entityType",
                "observations"
              ],
              "additionalProperties": false
            }
          },
          "relations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "description": "The name of the entity where the relation starts"
                },
                "to": {
                  "type": "string",
                  "description": "The name of the entity where the relation ends"
                },
                "relationType": {
                  "type": "string",
                  "description": "The type of the relation"
                }
              },
              "required": [
                "from",
                "to",
                "relationType"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "entities",
          "relations"
        ],
        "$schema": "http://json-schema.org/draft-07/schema#",
        "additionalProperties": false
      },
      "annotations": {
        "readOnlyHint": true,
        "destructiveHint": false,
        "idempotentHint": true,
        "openWorldHint": false
      }
    }
  }
};
