import { describe, expect, it } from "vitest";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ServerTarget } from "../src/cli/connect.js";
import { introspect } from "../src/cli/introspect.js";
import { check } from "../src/cli/check.js";
import { parseDtsSnapshot, parseSnapshotText, detectFormat } from "../src/cli/snapshot.js";

const EVERYTHING_SERVER = "node_modules/@modelcontextprotocol/server-everything/dist/index.js";

const target: ServerTarget = { command: "node", args: [EVERYTHING_SERVER] };

function tmpFile(name: string): string {
  const dir = mkdtempSync(join(tmpdir(), "mcp-tada-cli-test-"));
  return join(dir, name);
}

describe("introspect", () => {
  it("produces a .d.ts snapshot that parses back and contains get-sum", async () => {
    const out = tmpFile("introspection.d.ts");
    const result = await introspect({ target, out });
    expect(result.wrote).toBe(true);
    expect(result.text).toContain("// Generated by mcp-tada. Do not edit.");
    expect(result.text).toContain("export type introspection =");

    const parsed = parseDtsSnapshot(result.text);
    expect(parsed.tools["get-sum"]).toBeDefined();
    const getSum = parsed.tools["get-sum"];
    expect(getSum?.inputSchema).toMatchObject({
      type: "object",
      properties: {
        a: { type: "number" },
        b: { type: "number" },
      },
      required: ["a", "b"],
    });
    expect(getSum?.outputSchema).toBeUndefined();

    // tool keys are sorted
    const names = Object.keys(parsed.tools);
    expect(names).toEqual([...names].sort());

    // a tool with an outputSchema keeps it
    expect(parsed.tools["get-structured-content"]?.outputSchema).toBeDefined();
  }, 30_000);

  it("does not rewrite the file when content is unchanged", async () => {
    const out = tmpFile("introspection.d.ts");
    const first = await introspect({ target, out });
    expect(first.wrote).toBe(true);
    const second = await introspect({ target, out });
    expect(second.wrote).toBe(false);
    expect(second.text).toBe(first.text);
  }, 30_000);

  it("supports --json output that round-trips through JSON.parse", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    expect(result.wrote).toBe(true);
    const parsed = JSON.parse(result.text);
    expect(parsed.tools["get-sum"]).toBeDefined();
  }, 30_000);

  it("emits a JSDoc block with title/description above each tool", async () => {
    const out = tmpFile("introspection.d.ts");
    const result = await introspect({ target, out });
    expect(result.text).toMatch(
      /\/\*\*[\s\S]*?Get Sum Tool[\s\S]*?Returns the sum of two numbers[\s\S]*?\*\/\s*\n\s*"get-sum"/,
    );
  }, 30_000);

  it("supports a custom --name export alias", async () => {
    const out = tmpFile("introspection.d.ts");
    const result = await introspect({ target, out, name: "everything" });
    expect(result.text).toContain("export type everything = introspection;");
  }, 30_000);
});

describe("check", () => {
  it("reports no differences against a fresh snapshot", async () => {
    const out = tmpFile("introspection.d.ts");
    await introspect({ target, out });
    const { report } = await check({ target, against: out });
    expect(report.identical).toBe(true);
    expect(report.added).toEqual([]);
    expect(report.removed).toEqual([]);
  }, 30_000);

  it("reports a removed tool when the snapshot has one the live server no longer does", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as { tools: Record<string, unknown> };
    // Simulate a tool that existed when the snapshot was taken but has since been removed
    // from the live server, by injecting a tool into the snapshot that isn't live.
    data.tools["a-tool-that-no-longer-exists"] = { inputSchema: { type: "object" } };
    writeFileSync(out, JSON.stringify(data, null, 2));

    const { report } = await check({ target, against: out });
    expect(report.identical).toBe(false);
    expect(report.removed).toEqual(["a-tool-that-no-longer-exists"]);
  }, 30_000);
});

describe("snapshot round-trip", () => {
  it("parses a hand-written .d.ts snapshot with header comments and JSDoc", () => {
    const text = `// Generated by mcp-tada. Do not edit.
// server: demo@1.0.0
// protocolVersion: 2026-07-28

export type introspection = {
  "tools": {
    /**
     * Echo
     * Echoes a message back
     */
    "echo": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ]
      }
    }
  }
};

export type demo = introspection;
`;
    const data = parseDtsSnapshot(text);
    expect(data.tools["echo"]).toEqual({
      inputSchema: {
        type: "object",
        properties: { message: { type: "string" } },
        required: ["message"],
      },
    });
  });

  it("detects format from file extension", () => {
    expect(detectFormat("introspection.d.ts")).toBe("dts");
    expect(detectFormat("introspection.json")).toBe("json");
  });

  it("parseSnapshotText dispatches on format", () => {
    const json = JSON.stringify({ tools: { a: { inputSchema: { type: "object" } } } });
    expect(parseSnapshotText(json, "json")).toEqual({
      tools: { a: { inputSchema: { type: "object" } } },
    });
  });

  it("throws a helpful error when the marker is missing", () => {
    expect(() => parseDtsSnapshot("not a snapshot")).toThrow(/export type introspection/);
  });
});
