import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { writeFileSync } from "node:fs";
const t = new StdioClientTransport({ command: "node", args: ["node_modules/@modelcontextprotocol/server-everything/dist/index.js"] });
const c = new Client({ name: "mcp-tada-introspect", version: "0.0.0" });
await c.connect(t);
const caps = c.getServerCapabilities();
let tools = [], cursor;
do { const r = await c.listTools({ cursor }); tools.push(...r.tools); cursor = r.nextCursor; } while (cursor);
writeFileSync("introspection.d.ts",
  `// generated by mcp-tada introspect\nexport type introspection = ${JSON.stringify({ tools }, null, 2)};\n`);
console.log("capabilities.tools:", JSON.stringify(caps.tools));
console.log("tools:", tools.map(t => `${t.name}${t.outputSchema ? " [out]" : ""}`).join(", "));
await c.close();
