// generated by mcp-tada introspect
export type introspection = { tools: {
  "echo": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "description": "Message to echo"
        }
      },
      "required": [
        "message"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get-annotated-message": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "messageType": {
          "type": "string",
          "enum": [
            "error",
            "success",
            "debug"
          ],
          "description": "Type of message to demonstrate different annotation patterns"
        },
        "includeImage": {
          "default": false,
          "description": "Whether to include an example image",
          "type": "boolean"
        }
      },
      "required": [
        "messageType"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get-env": {
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get-resource-links": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "count": {
          "default": 3,
          "description": "Number of resource links to return (1-10)",
          "type": "number",
          "minimum": 1,
          "maximum": 10
        }
      },
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get-resource-reference": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "resourceType": {
          "default": "Text",
          "type": "string",
          "enum": [
            "Text",
            "Blob"
          ]
        },
        "resourceId": {
          "default": 1,
          "description": "ID of the text resource to fetch",
          "type": "number"
        }
      },
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get-structured-content": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "location": {
          "type": "string",
          "enum": [
            "New York",
            "Chicago",
            "Los Angeles"
          ],
          "description": "Choose city"
        }
      },
      "required": [
        "location"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "temperature": {
          "type": "number",
          "description": "Temperature in celsius"
        },
        "conditions": {
          "type": "string",
          "description": "Weather conditions description"
        },
        "humidity": {
          "type": "number",
          "description": "Humidity percentage"
        }
      },
      "required": [
        "temperature",
        "conditions",
        "humidity"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#",
      "additionalProperties": false
    }
  },
  "get-sum": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "a": {
          "type": "number",
          "description": "First number"
        },
        "b": {
          "type": "number",
          "description": "Second number"
        }
      },
      "required": [
        "a",
        "b"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "get-tiny-image": {
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "gzip-file-as-resource": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "default": "README.md.gz",
          "type": "string",
          "description": "Name of the output file"
        },
        "data": {
          "default": "https://raw.githubusercontent.com/modelcontextprotocol/servers/refs/heads/main/README.md",
          "type": "string",
          "format": "uri",
          "description": "URL or data URI of the file content to compress"
        },
        "outputType": {
          "default": "resourceLink",
          "description": "How the resulting gzipped file should be returned. 'resourceLink' returns a link to a resource that can be read later, 'resource' returns a full resource object.",
          "type": "string",
          "enum": [
            "resourceLink",
            "resource"
          ]
        }
      },
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "toggle-simulated-logging": {
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "toggle-subscriber-updates": {
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "trigger-long-running-operation": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "duration": {
          "default": 10,
          "description": "Duration of the operation in seconds",
          "type": "number"
        },
        "steps": {
          "default": 5,
          "description": "Number of steps in the operation",
          "type": "number"
        }
      },
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "simulate-research-query": {
    "inputSchema": {
      "type": "object",
      "properties": {
        "topic": {
          "type": "string",
          "description": "The research topic to investigate"
        },
        "ambiguous": {
          "default": false,
          "description": "Simulate an ambiguous query that requires clarification (triggers input_required status)",
          "type": "boolean"
        }
      },
      "required": [
        "topic"
      ],
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  }
} };
