import { describe, expect, it, vi } from "vitest";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ServerTarget } from "../src/cli/connect.js";
import { introspect } from "../src/cli/introspect.js";
import { check } from "../src/cli/check.js";
import { parseDtsSnapshot, parseSnapshotText, detectFormat } from "../src/cli/snapshot.js";
import { runCheckWith, runIntrospectWith } from "../src/cli/main.js";

const EVERYTHING_SERVER = "node_modules/@modelcontextprotocol/server-everything/dist/index.js";

const target: ServerTarget = { command: "node", args: [EVERYTHING_SERVER] };

function tmpFile(name: string): string {
  const dir = mkdtempSync(join(tmpdir(), "mcp-tada-cli-test-"));
  return join(dir, name);
}

describe("introspect", () => {
  it("produces a .d.ts snapshot that parses back and contains get-sum", async () => {
    const out = tmpFile("introspection.d.ts");
    const result = await introspect({ target, out });
    expect(result.wrote).toBe(true);
    expect(result.text).toContain("// Generated by mcp-tada. Do not edit.");
    expect(result.text).toContain("export type introspection =");

    const parsed = parseDtsSnapshot(result.text);
    expect(parsed.tools["get-sum"]).toBeDefined();
    const getSum = parsed.tools["get-sum"];
    expect(getSum?.inputSchema).toMatchObject({
      type: "object",
      properties: {
        a: { type: "number" },
        b: { type: "number" },
      },
      required: ["a", "b"],
    });
    expect(getSum?.outputSchema).toBeUndefined();

    // tool keys are sorted
    const names = Object.keys(parsed.tools);
    expect(names).toEqual([...names].sort());

    // a tool with an outputSchema keeps it
    expect(parsed.tools["get-structured-content"]?.outputSchema).toBeDefined();

    // annotations are recorded with their keys in spec order
    expect(parsed.tools["gzip-file-as-resource"]?.annotations).toBeDefined();
    expect(Object.keys(parsed.tools["gzip-file-as-resource"]?.annotations ?? {})).toEqual([
      "readOnlyHint",
      "destructiveHint",
      "idempotentHint",
      "openWorldHint",
    ]);
    expect(parsed.tools["get-sum"]?.annotations?.readOnlyHint).toBe(true);

    // prompts are recorded with their argument names and required flags, descriptions as @param
    expect(result.text).toContain("// capabilities.prompts.listChanged: true");
    expect(parsed.prompts?.["args-prompt"]).toEqual({
      arguments: [
        { name: "city", required: true },
        { name: "state", required: false },
      ],
    });
    expect(parsed.prompts?.["simple-prompt"]).toEqual({ arguments: [] });
    expect(result.text).toMatch(/@param city Name of the city\s*\n\s*\*\/\s*\n\s*"args-prompt"/);
    const promptNames = Object.keys(parsed.prompts ?? {});
    expect(promptNames).toEqual([...promptNames].sort());
  }, 30_000);

  it("does not rewrite the file when content is unchanged", async () => {
    const out = tmpFile("introspection.d.ts");
    const first = await introspect({ target, out });
    expect(first.wrote).toBe(true);
    const second = await introspect({ target, out });
    expect(second.wrote).toBe(false);
    expect(second.text).toBe(first.text);
  }, 30_000);

  it("supports --json output that round-trips through JSON.parse", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    expect(result.wrote).toBe(true);
    const parsed = JSON.parse(result.text);
    expect(parsed.tools["get-sum"]).toBeDefined();
    expect(parsed.prompts["args-prompt"].arguments[0]).toEqual({ name: "city", required: true });
  }, 30_000);

  it("refuses to write --json output to a .d.ts path, and a .d.ts snapshot to a .json path", async () => {
    await expect(
      introspect({ target, out: tmpFile("introspection.d.ts"), json: true, write: false }),
    ).rejects.toThrow(/--json writes raw JSON/);
    await expect(
      introspect({ target, out: tmpFile("introspection.json"), write: false }),
    ).rejects.toThrow(/pass --json/);
  });

  it("omits the protocolVersion header line when the transport does not expose it", async () => {
    const result = await introspect({ target, write: false });
    expect(result.text).not.toContain("protocolVersion");
  }, 30_000);

  it("emits a JSDoc block with title/description above each tool", async () => {
    const out = tmpFile("introspection.d.ts");
    const result = await introspect({ target, out });
    expect(result.text).toMatch(
      /\/\*\*[\s\S]*?Get Sum Tool[\s\S]*?Returns the sum of two numbers[\s\S]*?\*\/\s*\n\s*"get-sum"/,
    );
  }, 30_000);

  it("repeats each argument's description as a @param args.<name> tag in the tool's JSDoc", async () => {
    const result = await introspect({ target, write: false });
    expect(result.text).toMatch(
      /Returns the sum of two numbers\s*\n\s*\* @param args\.a First number\s*\n\s*\* @param args\.b Second number\s*\n\s*\*\/\s*\n\s*"get-sum"/,
    );
  }, 30_000);

  it("supports a custom --name export alias", async () => {
    const out = tmpFile("introspection.d.ts");
    const result = await introspect({ target, out, name: "everything" });
    expect(result.text).toContain("export type everything = introspection;");
  }, 30_000);
});

describe("check", () => {
  it("reports no differences against a fresh snapshot", async () => {
    const out = tmpFile("introspection.d.ts");
    await introspect({ target, out });
    const { report } = await check({ target, against: out });
    expect(report.identical).toBe(true);
    expect(report.added).toEqual([]);
    expect(report.removed).toEqual([]);
  }, 30_000);

  it("reports a removed tool when the snapshot has one the live server no longer does", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as { tools: Record<string, unknown> };
    // Simulate a tool that existed when the snapshot was taken but has since been removed
    // from the live server, by injecting a tool into the snapshot that isn't live.
    data.tools["a-tool-that-no-longer-exists"] = { inputSchema: { type: "object" } };
    writeFileSync(out, JSON.stringify(data, null, 2));

    const { report } = await check({ target, against: out });
    expect(report.identical).toBe(false);
    expect(report.removed).toEqual(["a-tool-that-no-longer-exists"]);
  }, 30_000);

  it("reports added, removed and changed prompts", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as {
      prompts: Record<string, { arguments: { name: string; required?: boolean }[] }>;
    };
    delete data.prompts["simple-prompt"]; // live has it, snapshot does not: added
    data.prompts["retired-prompt"] = { arguments: [] }; // snapshot has it, live does not: removed
    data.prompts["args-prompt"]!.arguments[1]!.required = true; // flag flipped: changed
    writeFileSync(out, JSON.stringify(data, null, 2));

    const { report, text } = await check({ target, against: out });
    expect(report.identical).toBe(false);
    expect(report.promptsAdded).toEqual(["simple-prompt"]);
    expect(report.promptsRemoved).toEqual(["retired-prompt"]);
    expect(report.promptsChanged).toEqual(["args-prompt"]);
    expect(text).toContain("args-prompt: prompt arguments changed");
  }, 30_000);

  it("treats a snapshot taken before prompts were recorded as having none", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as { prompts?: unknown };
    delete data.prompts;
    writeFileSync(out, JSON.stringify(data, null, 2));

    const { report } = await check({ target, against: out });
    expect(report.promptsAdded.length).toBeGreaterThan(0);
    expect(report.promptsRemoved).toEqual([]);
  }, 30_000);

  it("reports annotation drift, and separately a lost safety guarantee", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as {
      tools: Record<string, { annotations?: Record<string, unknown> }>;
    };
    // The snapshot promised more than the live server does: get-sum used to be read-only (it
    // is, live: readOnlyHint true) and gzip-file-as-resource used to be read-only too (it is
    // not, live), while echo only changes an unrelated hint.
    data.tools["gzip-file-as-resource"]!.annotations!.readOnlyHint = true;
    data.tools["echo"]!.annotations!.openWorldHint = true;
    // a tool the snapshot recorded without annotations, which the live server annotates
    delete data.tools["get-env"]!.annotations;
    writeFileSync(out, JSON.stringify(data, null, 2));

    const { report, text } = await check({ target, against: out });
    expect(report.identical).toBe(false);
    expect(report.annotationsChanged).toEqual(["echo", "get-env", "gzip-file-as-resource"]);
    expect(report.safetyWeakened).toEqual(["gzip-file-as-resource"]);
    expect(text).toContain("echo: annotations changed");
    expect(text).toContain("get-env: annotations changed");
    expect(text).toContain("gzip-file-as-resource: lost a safety guarantee");
    expect(report.severity).toBe("dangerous");
  }, 30_000);

  it("exits 0 on additive drift with --fail-on breaking, and 1 without it", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as { tools: Record<string, unknown> };
    // A tool the live server has and the snapshot does not: purely additive.
    delete data.tools["echo"];
    writeFileSync(out, JSON.stringify(data, null, 2));

    const flags = { command: `node ${EVERYTHING_SERVER}`, against: out };
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    try {
      expect(await runCheckWith({ ...flags, "fail-on": "breaking" })).toBe(0);
      expect(await runCheckWith({ ...flags, "fail-on": "dangerous" })).toBe(0);
      expect(errorSpy.mock.calls.flat().join("\n")).toContain(
        "passing because of --fail-on breaking",
      );
      expect(await runCheckWith(flags)).toBe(1);
      expect(await runCheckWith({ ...flags, "fail-on": "sometimes" })).toBe(1);
    } finally {
      errorSpy.mockRestore();
    }
  }, 60_000);

  it("exits 1 on breaking drift even with --fail-on breaking", async () => {
    const out = tmpFile("introspection.json");
    const result = await introspect({ target, out, json: true });
    const data = JSON.parse(result.text) as { tools: Record<string, unknown> };
    data.tools["a-tool-that-no-longer-exists"] = { inputSchema: { type: "object" } };
    writeFileSync(out, JSON.stringify(data, null, 2));

    const code = await runCheckWith({
      command: `node ${EVERYTHING_SERVER}`,
      against: out,
      "fail-on": "breaking",
    });
    expect(code).toBe(1);
  }, 30_000);
});

describe("snapshot round-trip", () => {
  it("parses a hand-written .d.ts snapshot with header comments and JSDoc", () => {
    const text = `// Generated by mcp-tada. Do not edit.
// server: demo@1.0.0
// protocolVersion: 2026-07-28

export type introspection = {
  "tools": {
    /**
     * Echo
     * Echoes a message back
     */
    "echo": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ]
      }
    }
  }
};

export type demo = introspection;
`;
    const data = parseDtsSnapshot(text);
    expect(data.tools["echo"]).toEqual({
      inputSchema: {
        type: "object",
        properties: { message: { type: "string" } },
        required: ["message"],
      },
    });
  });

  it("detects format from file extension", () => {
    expect(detectFormat("introspection.d.ts")).toBe("dts");
    expect(detectFormat("introspection.json")).toBe("json");
  });

  it("parseSnapshotText dispatches on format", () => {
    const json = JSON.stringify({ tools: { a: { inputSchema: { type: "object" } } } });
    expect(parseSnapshotText(json, "json")).toEqual({
      tools: { a: { inputSchema: { type: "object" } } },
    });
  });

  it("throws a helpful error when the marker is missing", () => {
    expect(() => parseDtsSnapshot("not a snapshot")).toThrow(/export type introspection/);
  });
});

describe("introspect --out with a config file", () => {
  function writeConfig(servers: Record<string, unknown>): string {
    const dir = mkdtempSync(join(tmpdir(), "mcp-tada-cli-config-"));
    const path = join(dir, "mcp-tada.config.json");
    writeFileSync(path, JSON.stringify({ servers }));
    return path;
  }

  it("exits 1 instead of writing every server to the same --out file", async () => {
    const config = writeConfig({
      one: { command: "node", args: [EVERYTHING_SERVER] },
      two: { command: "node", args: [EVERYTHING_SERVER] },
    });
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    try {
      const code = await runIntrospectWith({ config, out: "shared.d.ts" });
      expect(code).toBe(1);
      expect(errorSpy.mock.calls.flat().join("\n")).toMatch(/--out cannot be used with 2 servers/);
    } finally {
      errorSpy.mockRestore();
    }
  });

  it("allows --out when only one server is selected via the positional alias", async () => {
    const config = writeConfig({
      one: { command: "node", args: [EVERYTHING_SERVER] },
      two: { command: "node", args: [EVERYTHING_SERVER] },
    });
    const out = tmpFile("one.d.ts");
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    try {
      const code = await runIntrospectWith({ config, out, aliasFilter: "one" });
      expect(code).toBe(0);
    } finally {
      errorSpy.mockRestore();
    }
  }, 30_000);
});

describe("--timeout", () => {
  // A stdio "server" that never speaks MCP: connectClient (and, for check, introspectTarget's
  // tools/list) must time out instead of hanging.
  const silentTarget: ServerTarget = {
    command: "node",
    args: ["-e", "setTimeout(() => {}, 5_000)"],
    timeoutMs: 200,
  };

  it("introspect fails fast with a message naming the target", async () => {
    await expect(introspect({ target: silentTarget, write: false })).rejects.toThrow(/timed out/);
  }, 10_000);

  it("names the target and the cause when a URL cannot be reached", async () => {
    const target: ServerTarget = {
      url: "https://this-domain-does-not-exist-mcp-tada.invalid/mcp",
      timeoutMs: 10_000,
    };
    await expect(introspect({ target, write: false })).rejects.toThrow(
      /connecting to "https:\/\/this-domain-does-not-exist-mcp-tada\.invalid\/mcp" failed: fetch failed \(/,
    );
  }, 20_000);

  it("check fails fast with a message naming the target", async () => {
    const out = tmpFile("introspection.json");
    writeFileSync(out, JSON.stringify({ tools: {} }));
    await expect(check({ target: silentTarget, against: out })).rejects.toThrow(/timed out/);
  }, 10_000);
});
