// Generated by mcp-tada. Do not edit.
// server: notes@0.1.0
// protocolVersion: unknown
// capabilities.tools.listChanged: false

export type introspection = {
  "tools": {
    /**
     * Store a note and return it with its assigned id.
     */
    "add_note": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Short title"
          },
          "body": {
            "type": "string",
            "description": "Note contents"
          }
        },
        "required": [
          "title",
          "body"
        ],
        "additionalProperties": false
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "title",
          "body"
        ]
      }
    },
    /**
     * Delete every note. Returns plain text, no structured output.
     */
    "clear_notes": {
      "inputSchema": {
        "type": "object",
        "properties": {}
      }
    },
    /**
     * Fetch one note by id. Returns an error result when the id is unknown.
     */
    "get_note": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          }
        },
        "required": [
          "id"
        ]
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "title",
          "body"
        ]
      }
    },
    /**
     * List every stored note.
     */
    "list_notes": {
      "inputSchema": {
        "type": "object",
        "properties": {}
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "notes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "title": {
                  "type": "string"
                },
                "body": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "title",
                "body"
              ]
            }
          }
        },
        "required": [
          "notes"
        ]
      }
    }
  }
};
