/* eslint-disable */
// Generated by mcp-tada. Do not edit.
// server: DeepWiki@2.14.3
// protocolVersion: 2025-11-25
// capabilities.tools.listChanged: true

/* prettier-ignore */
export type introspection = {
  "tools": {
    /**
     * Ask any question about a GitHub repository and get an AI-powered, context-grounded response.
     */
    "ask_question": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "repoName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "items": {
                  "type": "string"
                },
                "type": "array"
              }
            ],
            "description": "GitHub repository or list of repositories (max 10) in owner/repo format."
          },
          "question": {
            "description": "The question to ask about the repository.",
            "type": "string"
          }
        },
        "required": [
          "repoName",
          "question"
        ]
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "result": {
            "type": "string"
          }
        },
        "required": [
          "result"
        ],
        "x-fastmcp-wrap-result": true
      }
    },
    /**
     * View documentation about a GitHub repository.
     */
    "read_wiki_contents": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "repoName": {
            "description": "GitHub repository in owner/repo format (e.g. \"facebook/react\").",
            "type": "string"
          }
        },
        "required": [
          "repoName"
        ]
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "result": {
            "type": "string"
          }
        },
        "required": [
          "result"
        ],
        "x-fastmcp-wrap-result": true
      }
    },
    /**
     * Get a list of documentation topics for a GitHub repository.
     */
    "read_wiki_structure": {
      "inputSchema": {
        "type": "object",
        "properties": {
          "repoName": {
            "description": "GitHub repository in owner/repo format (e.g. \"facebook/react\").",
            "type": "string"
          }
        },
        "required": [
          "repoName"
        ]
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "result": {
            "type": "string"
          }
        },
        "required": [
          "result"
        ],
        "x-fastmcp-wrap-result": true
      }
    }
  }
};
